global:
  scrape_interval: 10s
scrape_configs:
  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://eva2-campaign-manager.staging.jlr-ddc.com/
        - https://eva2-campaign-manager.pre-prod.jlr-ddc.com/
        - https://eva2-campaign-manager.jlr-ddc.com/
        - https://sonar.services.jlr-ddc.com/projects
    relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: host.docker.internal:9115 #blacbox exporter
